### ISSUE TITLE
Config file settings not applied in neovim

### ISSUE THREAD

**Issue by r-vdp** [tekumara/typos-lsp#55]
I have setup typos-lsp like this:
```lua
local xdg_config_home = vim.env.XDG_CONFIG_HOME or (vim.env.HOME .. "/.config")
local nvim_lsp = require("lspconfig")
local capabilities = vim.lsp.protocol.make_client_capabilities()

local on_attach = function(client, bufnr)
  -- A bunch of keybindings and autocommands
end

nvim_lsp.typos_lsp.setup({
  on_attach = on_attach,
  capabilities = capabilities,
  init_options = {
    diagnosticSeverity = "hint",
    config = xdg_config_home .. "/typos.toml",
  }
})
```

This works great, and using `inotifywait` I can see that the config file is indeed opened when the lsp server starts.

The config file looks like this:
```toml
[default]
extend-ignore-re = ["snd-hda-intel"]
locale = "en-gb"
[default.extend-identifiers]

[default.extend-words]
```

When I run `typos --config ~/.config/typos.toml` on my project directory, `snd-hda-intel` is ignored as it should, however in neovim it's still shown as a typo.

Is typos-lsp somehow not passing the config file to typos?
